site_name: Awesome Reykjavík
theme:
  name: material
  language: en
repo_name: jokull/awesome-reykjavik
repo_url: https://github.com/jokull/awesome-reykjavik
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - toc:
      permalink: true
nav:
    - Home: 'index.md'
    - 'Guides':
        - 'Neighbourhoods': 'guides/neighbourhoods.md'
        - 'Driver’s license': 'guides/drivers-license.md'
        - 'Mobile plan': 'guides/mobile-phones.md'
        - 'Public transport': 'guides/public-transport.md'
        - 'Bank account': 'guides/bank-account.md'
        - 'Getting a car': 'guides/getting-a-car.md'
        - 'Auðkenni (Electronic certificate)': 'guides/audkenni.md'
        - 'Getting help': 'guides/getting-help.md'
        - 'Icelanders': 'guides/icelanders.md'
        - 'Kennitala': 'guides/kennitala.md'
        - 'Working in Iceland': 'guides/working-in-iceland.md'
        - 'Language': 'guides/language.md'
