site_name: Awesome Reykjavík
theme:
  name: material
  language: en
repo_name: jokull/awesome-reykjavik
repo_url: https://github.com/jokull/awesome-reykjavik
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - toc:
      permalink: true
  - footnotes
nav:
  - 'Home': 'index.md'
  - 'Neighbourhoods': 'guides/neighbourhoods.md'
  - 'Driver’s License': 'guides/drivers-license.md'
  - 'Mobile Plan': 'guides/mobile-phones.md'
  - 'Public Transport': 'guides/public-transport.md'
  - 'Bank Account': 'guides/bank-account.md'
  - 'Getting a Car': 'guides/getting-a-car.md'
  - 'Auðkenni (Electronic certificate)': 'guides/audkenni.md'
  - 'Getting Help': 'guides/getting-help.md'
  - 'Icelanders': 'guides/icelanders.md'
  - 'Kennitala': 'guides/kennitala.md'
  - 'Working in Iceland': 'guides/working-in-iceland.md'
  - 'International Schools': 'guides/international-schools.md'
  - 'The Local Tech Scene': 'guides/tech-scene.md'
  - 'Language': 'guides/language.md'
  - 'Groceries': 'guides/groceries.md'
